In [27]:
import pandas as pd
import numpy as np

from surprise import NormalPredictor
from surprise import Dataset
from surprise import Reader

from collections import defaultdict

from surprise import SVD
from surprise import Dataset

# Creation of new dataset

In [28]:

n_user=200
n_food=192
n_interaction=100
df = pd.DataFrame(dict(
    userID=np.random.randint(1, n_user, size=n_interaction),
    foodID=np.random.randint(1, n_food, size=n_interaction),
    rating=np.random.randint(1,2,size=n_interaction)
))
reader = Reader()

data = Dataset.load_from_df(df[['userID', 'foodID', 'rating']], reader)
df

    userID  foodID  rating
0      150     182       1
1       37     100       1
2       78     100       1
3      151      85       1
4      120     146       1
..     ...     ...     ...
95     176      35       1
96      58     129       1
97     149      88       1
98      76      84       1
99      16      67       1

[100 rows x 3 columns]

# top-n recommendation

In [29]:
def get_top_n(predictions, n=10):
   
    top_n = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        top_n[uid].append((iid, est))

    for uid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[1], reverse=True)
        top_n[uid] = user_ratings[:n]

    return top_n

# predict

In [30]:
trainset = data.build_full_trainset()
algo = SVD()
algo.fit(trainset)

testset = trainset.build_anti_testset()
predictions = algo.test(testset)

top_n = get_top_n(predictions, n=10)

for uid, user_ratings in top_n.items():
    print(uid, [iid for (iid, _) in user_ratings])

150 [121, 56, 1, 164, 173, 81, 76, 8, 174, 161]
37 [182, 84, 105, 83, 54, 48, 64, 126, 43, 15]
78 [74, 88, 184, 80, 26, 48, 183, 129, 1, 56]
151 [84, 35, 101, 96, 159, 105, 185, 111, 100, 80]
120 [161, 177, 184, 113, 119, 168, 92, 59, 50, 65]
96 [140, 74, 164, 65, 168, 183, 76, 165, 119, 36]
46 [80, 15, 83, 88, 100, 94, 85, 70, 39, 43]
41 [128, 105, 39, 104, 92, 179, 17, 140, 178, 2]
90 [140, 178, 183, 46, 17, 150, 128, 92, 35, 170]
142 [112, 100, 126, 96, 183, 165, 80, 35, 181, 42]
87 [27, 178, 56, 17, 80, 126, 105, 121, 137, 150]
145 [181, 127, 137, 146, 179, 39, 70, 112, 100, 126]
196 [92, 127, 17, 128, 170, 160, 96, 186, 76, 72]
191 [96, 181, 137, 39, 70, 173, 177, 114, 54, 164]
108 [1, 80, 67, 29, 182, 85, 35, 159, 110, 185]
85 [101, 80, 114, 64, 105, 111, 67, 165, 48, 110]
24 [177, 48, 178, 127, 39, 15, 17, 50, 101, 65]
5 [130, 94, 186, 160, 65, 91, 142, 96, 74, 181]
186 [114, 183, 139, 43, 168, 105, 161, 70, 15, 42]
68 [26, 64, 179, 8, 146, 153, 129, 67, 42, 161]
187 [46, 121, 119, 111, 160, 153, 43, 182, 25, 183]
159 [25, 142, 83, 48, 91, 96, 178, 17, 101, 54]
147 [75, 168, 39, 126, 119, 2, 159, 181, 70, 36]
177 [48, 179, 29, 64, 114, 186, 83, 94, 54, 105]
112 [48, 83, 126, 54, 181, 100, 59, 46, 177, 142]
158 [161, 114, 39, 96, 129, 183, 81, 50, 137, 181]
53 [168, 15, 27, 140, 8, 92, 59, 113, 42, 159]
49 [72, 179, 104, 64, 96, 114, 129, 121, 164, 2]
175 [142, 127, 75, 84, 153, 39, 137, 160, 67, 126]
15 [84, 81, 42, 113, 159, 35, 110, 181, 121, 75]
156 [112, 174, 35, 178, 96, 160, 72, 142, 179, 184]
29 [96, 114, 26, 140, 159, 39, 85, 164, 1, 84]
93 [140, 114, 85, 8, 64, 153, 105, 129, 136, 184]
38 [139, 84, 35, 161, 153, 101, 29, 46, 142, 110]
193 [42, 119, 45, 113, 59, 159, 128, 146, 25, 112]
45 [142, 112, 42, 83, 126, 35, 46, 150, 29, 84]
137 [101, 153, 8, 110, 173, 46, 92, 121, 61, 178]
58 [48, 27, 185, 15, 165, 59, 182, 130, 100, 146]
184 [111, 174, 75, 121, 56, 85, 179, 161, 181, 45]
128 [80, 161, 17, 126, 35, 177, 101, 173, 181, 15]
73 [184, 174, 65, 75, 48, 83, 27, 186, 80, 100]
148 [182, 174, 39, 164, 139, 54, 64, 126, 80, 159]
27 [104, 161, 112, 75, 153, 96, 114, 48, 170, 2]
67 [39, 142, 36, 129, 159, 119, 185, 45, 128, 153]
18 [140, 105, 136, 121, 91, 48, 8, 54, 142, 165]
168 [65, 36, 17, 92, 72, 161, 177, 15, 114, 186]
140 [39, 126, 83, 165, 182, 142, 137, 36, 17, 48]
199 [183, 161, 46, 119, 129, 76, 42, 101, 50, 181]
125 [70, 113, 72, 45, 150, 185, 74, 168, 140, 121]
136 [2, 111, 183, 36, 161, 114, 74, 177, 178, 43]
110 [50, 177, 136, 39, 179, 46, 113, 56, 161, 76]
21 [54, 45, 150, 59, 129, 64, 179, 48, 70, 165]
28 [15, 91, 142, 50, 161, 8, 184, 130, 54, 65]
42 [46, 39, 59, 45, 36, 84, 121, 42, 161, 177]
11 [174, 80, 36, 150, 76, 173, 88, 27, 17, 139]
118 [178, 8, 94, 121, 85, 182, 164, 1, 100, 96]
13 [130, 186, 159, 181, 100, 84, 65, 174, 126, 150]
80 [183, 67, 85, 39, 1, 65, 83, 105, 161, 114]
117 [35, 2, 140, 183, 56, 72, 81, 174, 179, 178]
129 [25, 130, 139, 164, 183, 94, 39, 178, 159, 46]
56 [142, 48, 54, 50, 43, 112, 160, 91, 129, 70]
74 [150, 168, 165, 35, 76, 159, 42, 84, 80, 128]
123 [45, 113, 186, 100, 81, 114, 174, 160, 170, 54]
50 [74, 129, 81, 54, 46, 161, 111, 91, 83, 100]
197 [48, 105, 112, 177, 88, 67, 173, 29, 168, 130]
194 [119, 110, 177, 83, 84, 183, 105, 113, 170, 46]
60 [64, 100, 43, 91, 165, 110, 83, 161, 59, 159]
95 [92, 1, 121, 146, 128, 56, 39, 119, 101, 26]
176 [181, 139, 54, 177, 186, 25, 112, 160, 179, 153]
149 [179, 113, 112, 185, 101, 174, 45, 186, 72, 130]
76 [25, 15, 76, 160, 100, 186, 177, 165, 39, 130]
16 [17, 72, 64, 137, 45, 61, 184, 139, 114, 161]